name: Greeting
on: [push, workflow_dispatch]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # uses: actions/checkout@v3
        run: echo "Checked out repository"
